# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  CHIP_8_config = debug_x86

else ifeq ($(config),debug_x64)
  CHIP_8_config = debug_x64

else ifeq ($(config),release_x86)
  CHIP_8_config = release_x86

else ifeq ($(config),release_x64)
  CHIP_8_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CHIP-8

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CHIP-8:
ifneq (,$(CHIP_8_config))
	@echo "==== Building CHIP-8 ($(CHIP_8_config)) ===="
	@${MAKE} --no-print-directory -C CHIP-8 -f Makefile config=$(CHIP_8_config)
endif

clean:
	@${MAKE} --no-print-directory -C CHIP-8 -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x64"
	@echo "  release_x86"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CHIP-8"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"